services:
    blog:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: blog
        restart: unless-stopped
        networks:
            - neurythm-prod

networks:
    neurythm-prod:
        external: true
